### ISSUE TITLE
"This message could not be saved"

### ISSUE THREAD

**Issue by dwrhodes** [hankhank10/loglink-server#28]
I haven't used loglink in a week or so, but when I do now, I get the repeated responses "This message could not be saved" in Telegram.

**Comment by hankhank10** [comment]
Thank you.

I am not experiencing this issue, so it must be an issue with your account rather than the service overall.

Please could I ask you to check the following:

- Try sending a plain text message (if you were trying to send eg a photo)
- Request a token reset using /token

Please do report back if that fixes the issue or not.

Thanks

**Comment by hankhank10** [comment]
Thank you for reporting this. I believe I have found and fixed the error.

LogLink does not support sending documents at the moment: only text, images and locations.

If a user attempts to send a document then previously the server returned an unhelpful error message to the user (not explaining the issue) and importantly also reported an error back to Telegram. That meant that Telegram thought it had done something wrong and repeatedly tried to re-deliver the document.

As of commit 150fe4c9b0dcb4d283ccfe0d023fc699b8c04a14 the server now does the following:
- Reports a more user friendly error to the user
- Tells Telegram that it did its job by delivering the message and that it doesn't need to send it again

@dwrhodes I would be grateful if you could test whether your issue is now resolved.

Thanks

**Comment by dwrhodes** [comment]
Thanks for the quick response. That tracks with what I did. I was testing the Voiceliner app, trying to export an outline through LogLink to Logseq. I checked the box for "as .md file" the first time, so that's what broke it. Even though I unchecked it for subsequent tries, they wouldn't go through.  Since your fix, they all came through, and all tests since then have worked.

This is a great way to get mobile content into Logseq. Good luck with the project.

**Comment by hankhank10** [comment]
Thanks for confirming @dwrhodes, closing this issue in that case - please reopen if you face future issues.

**Comment by xoyk** [comment]
No, the bug is still there. It really reproducible if you try to send audio, or video content (or forward a Telegram post with such content. Actually, right now it is the only reason why I am thinking about stopping using the plugin. 

My report is here: https://github.com/hankhank10/loglink-plugin/issues/7

**Comment by xoyk** [comment]
@hankhank10 

![Screenshot 2023-04-10 at 13 55 56](https://user-images.githubusercontent.com/1499826/230888893-40d7398a-f493-48d3-9db0-140bcadf4542.png)
That is a response to sending unsupported content (a forwarded post with video). 
So, I can assume that the bug is still there.
