### ISSUE TITLE
Could not creat account with beta access code

### ISSUE THREAD

**Issue by kltehb** [hankhank10/loglink-server#39]
I received 2 beta access codes in 2 separate emails sent at pretty much the same time to my email.

I tried using each of these in Telegram with the /start command but neither was successful. For both, the reply in Telegram was the same - 'There was a problem creating your account'

**Comment by hankhank10** [comment]
Thank you @kltehb for flagging this.

Please could I ask the following to help me troubleshoot this:
- Please could you post here a screenshot of the message you sent on Telegram and the response
- Please could you also let me know your email address and I will try sending another code to you to see if this resolves it

Thank you

**Comment by kltehb** [comment]
As requested.

![IMG_FD29A5EC8934-1](https://github.com/hankhank10/loglink-server/assets/65815562/d760e04a-ff86-4933-b9b8-76312aadbc58)

My email address is klteh.g@gmail.com

**Comment by hankhank10** [comment]
Great, thank you. Another invite coming to you shortly by email. Please could I ask that you completely close down the bot and restart it before trying the new code?

**Comment by hankhank10** [comment]
I think I've found the root of the issue @kltehb - please try again now

**Comment by kltehb** [comment]
Thanks for the 3rd betacode. It turned out I didn't have to use it, although I keyed it in with /start but subsequently realized that the telegram token was sent (presumably after you fixed the problem). I have set it up in logseq and successfully sent myself a test message!👍🏻

The interaction with the loglink bot in Telegram is confusing because the bot kept resending the same messages once I contacted it and before I can key in /start. If you can make the bot wait a certain amount of time for input before it send the messages, it may be helpful for users trying to get their token. This is my suggestion.

**Comment by hankhank10** [comment]
Thank you. There was an issue in the code that is now fixed that led to you getting multiple messages.

When LogLink received an opening message that isn't a correct beta code it sends back an error message in text to display to the user (which is appropriate) but I also had it set to send an HTTP error code. This sort of makes sense, but Telegram interpreted the error code as meaning the original message hadn't been delivered, so it would try to send it again, and get an error code back, and then conclude that that one hadn't been delivered so send again, etc.

Hence why you kept getting the same error message back, because Telegram was continually sending the same message thinking it was undelivered.

I have fixed this now so should be resolved.

Closing this issue now but please do raise another if you have issues.

**Comment by kltehb** [comment]
Great and prompt work! Thanks! Will continue to use it and flag any other
issues I come across.

Best regards,
